### ISSUE TITLE
Database Schema for User Profile

### ISSUE THREAD

**Issue by peironggg** [VantageSG/Vantage#13]
# Task
There is a need to come up with a Database Schema for User authentication and user profile for #10 #14 

# Schema
![Vantage Schema](https://user-images.githubusercontent.com/35712975/70930955-5a80b880-2071-11ea-95b5-2a37f94981c4.jpg)

- [x] Come up with database Schema
- [ ] Implement into code base

**Comment by klementtan** [comment]
@peironggg for now only need `User` and `UserProfile`.
