### ISSUE TITLE
[Feature] Landing Page

### ISSUE THREAD

**Issue by klementtan** [VantageSG/Vantage#15]
**Is your feature request related to a problem? Please describe.**
There is a need to provide the business side with content to pitch to potential clients and users.

**Describe the solution you'd like**
Deploy a static webpage from the main repo that contain information `About Us`

**Describe alternatives you've considered**
Create a separate repository for the `AboutUs` page

**Additional context**

**Comment by EugeneTeu** [comment]
I'll put in a template first. Currently Navbar is already set up. 

The separate repo for the About us page means i create a new project and repo ah
